### ISSUE TITLE
Allow v() in CSS functions (calc, repeat…)

### ISSUE THREAD

**Issue by meduzen** [meduzen/v-helper#4]
Because of how [`SCSS` interpolation works](https://github.com/meduzen/v-helper#edge-cases), `v()` can’t be used in `calc()`, `repeat()` and some others.

```scss
.selector {
  left: calc(v(weeks, 3) * 7); // doesn’t work
  left: calc(var(--weeks, 3) * 7); // works
}
```

Two ideas: either create passthrough functions (like in [true-hsl.scss](https://github.com/meduzen/true-hsl.scss)) either create as many vfunctions as needed: `vcalc()` `vrepeat()`…

Could be like this:
```scss
.selector {
  left: vcalc(v(weeks, 3) * 7);
}
```

Feasibility and idea to be discussed.
