### ISSUE TITLE
Add cascade of custom properties ending by fallback

### ISSUE THREAD

**Issue by meduzen** [meduzen/v-helper#5]
A [cool idea](https://twitter.com/doctype_jon/status/1253759449505755136) by Jonathan Dallas and @mirisuzanne ([pen](https://codepen.io/mirisuzanne/pen/GRpmOjr?editors=0100)).

The cascade proposed:

```scss
.my-class {
  color: varCascade(
      —btn-state,
      —btn-type,
      —btn-theme,
      blue /* fallback */
  );
}
```

How it could looks like in `v.scss`:
```scss
.my-class {
  color: v(btn-state, btn-type, btn-theme, blue);
}
```
