### ISSUE TITLE
Opportunity to save 2 bytes when the last fallback is `null`

### ISSUE THREAD

**Issue by meduzen** [meduzen/v-helper#7]
Not a bug, but an opportunity for improvement.

Taking this exemple:

```scss
.button {
  color: v(button-color, primary, null); // null = no final callback
}
```

It outputs:

```css
.button {
  color: var(--button-color, var(--primary, ));
}
```

It’s a valid output, but it would make more sense and save two bytes to get the following output:

```css
.button {
  color: var(--button-color, var(--primary));
}
```
