### ISSUE TITLE
Edge case: property can take coma-separated values

### ISSUE THREAD

**Issue by meduzen** [meduzen/v-helper#8]
Considering this:

```scss
.my-class {
  transition-property: var(--transition-properties, opacity, visibility)
}
```

~~This is not possible to get the same result with `v()` because it will wrap `opacity` as custom property name (`var(--opacity`). In this case, `v()` shouldn’t be used.~~ See next comment. 🤓

**Comment by meduzen** [comment]
Actually it’s possible by wrapping them in quotes:

```scss
.my-class {
  transition-property: v(transition-properties, 'opacity, visibility')
}
```

**Comment by meduzen** [comment]
It turns out the previous example is wrong because it generates:

```css
.my-class {
  transition-property: var(--transition-properties, 'opacity, visibility')
}
```

As [described on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/var#sect1), the quotes are not needed.

I think there are two _futures_ for this issue:
1. Mark the multiple fallbacks as unsupported.
2. Unquote the fallback parameter in such use cases.

I’d rather give a try at option 2 in order to improve the package.
